# Settings {#sec-gui-settings}

## Input {#input-settings}

The following options are available when creating or editing a project.

**Folder/file to analyze**: enter into here the folder or file to analyze.

**Subfolders/files to ignore**: enter into this list the folders and files to ignore.

::: {.tipsection data-latex=""}
Folder and file paths being ignored must be absolute or relative to the folder being analyzed.
:::

{{< pagebreak >}}

## Source Code

The following options are available for C/C++ source files.

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Run the following checks
:::

**Strings not exposed for translation**: select this to check for strings not exposed for translation.

**Ignore strings assigned to variables named**: when finding strings not exposed for translation, strings can be ignored if assigned to variables from this list.
For example, if a list of color names are assigned to a variable named `colorMode` that you wish to ignore, then add "colorMode" to this list.
You can enter variable names (e.g., "`colorMode`") or regular expressions (e.g., "`(RELEASE|DEBUG)check[0-9]?`") here.

::: {.notesection data-latex=""}
Adding a new entry here for a project will also add it to the global settings.
This will ensure that you don't have to re-enter these values for future projects.
:::

**Translatable strings that shouldn\'t be**: select this to check for translatable strings that should not be (e.g., numbers, keywords, `printf()` commands).

**Translatable strings being used in debug functions**: select this to check for translatable strings being used in internal contexts (e.g., debugging and console functions).

**Translatable strings that contain URLs or email addresses**: select this to check for translatable strings that contain URLs or email addresses.
It is recommended to dynamically format these into the string so that translators do not have to manage them.

**Translatable strings that are surrounded by spaces**: select this to check for translatable strings that start or begin with spaces.
(This is limited to actual space characters, and does not include tabs or newlines.)

These may be strings that are concatenated at runtime, which does not follow best i18n practices.
It is recommended to format separate values into a single string via a `printf` formatting function, rather than
piecing them together.

::: {.notesection data-latex=""}
An exception is made for strings that end with a colon followed by a space (": ").
It is assumed that this part of tabular data being concatenated and will be ignored.
:::

**Check for ambiguous strings that lack a translator comment**: select this to check for possibly ambiguous strings that lack a translator comment.

**Deprecated macros and functions**: select this to check for deprecated text macros and functions.
This will detect the usage of functions that are no longer relevant, and provide a suggested replacement.

For example, the `TCHAR` functions and macros used in Win32 programming (e.g., `_TEXT`, `_tcscmp`) to help target Windows 98 and NT are no longer necessary.
`Cuneiform` will recommend how to remove or replace these.

**printf functions being used to just format a number**: select this to check for `printf()`-like functions being used to just format a number.
In these situations, it is recommended to use the more modern `std::to_[w]string()` function.
This is limited to integral values; `printf()` commands with floating-point precision will be ignored.

**Malformed syntax in strings**: select this to check for malformed syntax in strings (e.g., malformed HTML tags).
::::

**Strings passed to logging functions can be translatable**: select this if it should be acceptable to pass translatable strings to logging functions.
Setting this to `false` will emit warnings when a translatable string is passed to functions such as `wxLogMessage`, `g_message`, or `qCWarning`.

**Exception messages should be available for translation**: select this to verify that exception messages are available for translation.
Setting this to `true` will emit warnings when untranslatable strings are passed to various exception constructors or functions
(e.g., `AfxThrowOleDispatchException`).

**Punctuation only strings can be translatable**: select this if it should be acceptable for punctuation only strings to be translatable.
Setting this to `true` will suppress warnings about strings such as "*? - ?*" being available for localization.

**Minimum words for a string to be considered translatable**: enter into here the minimum number of words that a string must have to be considered translatable.
Higher values for this will result in less strings being classified as `notL10NAvailable` warnings.

**C++ standard when issuing deprecation warnings**: enter into here the C++ standard that should be assumed when issuing deprecated macro warnings (`deprecatedMacro`).
For example, setting this to `2017` or higher (along with selecting the **Include verbose warnings** option) will issue warnings for `WXUNUSED`, as it can be replaced with `[[maybe_unused]]`.
If setting this to `2014`, however, `WXUNUSED` will be ignored since `[[maybe_unused]]` requires C++17.

**Include verbose warnings**: select this to perform additional checks, including those that may not be related to i18n/l10n issues.
This will also include additional information in the **Analysis Log** window.

{{< pagebreak >}}

## Resource Files

The following options are available for resource files (i.e., \*.po and \*.rc).

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Translation catalogs
:::

**Check for inconsistent printf format specifiers**: select this to check for mismatching `printf()` commands between source and translation strings.

::: {.warningsection data-latex=""}
The checks performed here are strict; all `printf()` commands in translations must match
their source counterpart exactly. For example, "*%lu*" vs. "*%l*" will emit a warning.
Questionable commands such as "*% s*" (space is only meant for numeric formatting) will also emit a warning.
:::

**Check for inconsistent keyboard accelerators**: select this to check for mismatching keyboard accelerators between source and translation strings.
This is performed by checking that both strings contain one '&' followed by an alphanumeric character.

**Check for inconsistent casing or trailing punctuation, spaces, or newlines**: select this to check for mismatching trailing punctuation, spaces, or newlines between source and translation strings.
This will also emit a warning if the source starts with an uppercase letter and the translation starts with a lowercase letter.

In regards to punctuation, terminating characters such as periods, exclamation points, and question marks are reviewed. For these, warnings will only be emitted if the source string
has a terminating mark and the translation does not have either a terminating mark or closing parenthesis. All types of terminating marks are treated interchangeably, as not all languages
commonly use question and exclamation marks as much as English.

**Review fuzzy translations**: select this to review fuzzy translations. This should only be selected if you intend to review translations
that still require approval and are likely unfinished.

::::

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Translation catalogs (*continued...*)
:::

**Pseudo-translation**

While analyzing translation catalogs, copies of them can also be created and be pseudo-translated.
Later, these catalogs can be loaded by your application for integration testing.

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Method
:::

This option specifies how to generate pseudo-translations.

**None (do not generate anything)**: instructs the program to not generate any files.

**UPPERCASE**: translations will be uppercased variations of the source strings.

**European characters**: letters and numbers from the source string will be replaced with accented variations.
The translation will be clearly different, but still generally readable.

**Fill with \'X\'es**: letters from the source string will be replaced with either \'x\' or \'X\' (matching the original casing).
This will produce the most altered appearance for the pseudo-translations.

During integration testing, these pseudo-translations will be easier to spot, but will make navigating the UI more difficult.
This is recommended for the quickest way to interactively find UI elements that are not being made available for translation.
::::

**Add surrounding brackets**: select this option to add brackets around the pseudo-translations.
This can help with identifying truncation and strings being pieced together at runtime.

**Add tracking IDs**: select this to add a unique ID number (inside or square brackets) in front of every pseudo-translation.
This can help with finding where a particular translation is coming from.

**Increase width**: select how much wider (between 0--100%) to make pseudo-translations.
This widening is done by padding the strings with hyphens on both sides.

The default is 40, as "German and Spanish translations can sometimes take 40% more screen space than English" [@boyero].

::: {.notesection data-latex=""}
If surrounding brackets or tracking IDs are being included, then their lengths will be factored into the increased width calculation.
:::
::::

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Windows RC files
:::

**Check for font issues**: select this to check for dialogs that use unusual font sizes
or are not using \'MS Shell Dlg\'.
::::

::: {.notesection data-latex=""}
Some static analysis options from the **Source Files** section will also be used while analyzing the source strings
in these resource files.
:::

{{< pagebreak >}}

## Additional Checks

The following additional options are available for C/C++ source files.
These options do not relate to internationalization, but are offered as supplemental checks for code formatting and other issues.

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Formatting & encoding checks
:::

**Non-UTF8 encoded files**: select this to check that files containing extended ASCII characters are UTF-8 encoded.
UTF-8 is recommended for compiler portability.

**BOM/UTF-8 signatures**: select this to check for UTF-8 encoded files which start with a BOM/UTF-8 signature.
It is recommended to save without the file signature for best compiler portability.

**Unencoded extended ASCII characters**: select this to check for strings containing extended ASCII characters that are not encoded.

**Trailing spaces**: select this to check for trailing spaces at the end of each line.

**Tabs**: select this to check for tabs.
(Spaces are recommended as tabs may appear differently between editors.)

**Overly long lines**: select this to check for overly long lines.

**Comments not starting with a space**: select this to check that there is a space at the start of a comment.
::::

:::: {.optionssection data-latex=""}
::: {.optionssectiontitle data-latex=""}
Code checks
:::

**Hard-coded ID numbers**: select this to check for ID variables being assigned a hard-coded number.
It may be preferred to assign framework-defined constants (e.g., `wxID_HIGHEST`) to IDs.

**ID variables assigned the same value**: select this to check for the same value being assigned to different ID variables.
This check is performed per file; the same ID being assigned multiple times, but within separate files, will be ignored.
::::