/*
DO NOT EDIT.
This is generated by Cmake. Re-configure the CMake file to update.
*/

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by i18ngui.rc
//
#define MANIFEST_RESOURCE_ID            1
#define wxBITMAP_STD_COLOURS            103
#define IDI_ICON1                       105
#define IDI_ICON2                       106
#define IDI_ICON3                       108
#define IDI_HELP_ICON                   108
#define IDI_APP_ICON                    109
#define ID_Menu                         40001

#define _I18NGUI_PROGRAM_VERSION_RC "2024.0.0.0"
#define _I18NGUI_FILE_VERSION_RC 2024,0,0,0
#define _I18NGUI_PRODUCUCT_VERSION_RC 2024,0,0,0
#define _I18NGUI_COPYRIGHT_RC "Copyright (C) 2024"
#define _I18NGUI_DESCRIPTION "i18n-check GUI"
#define _I18NGUI_BINARY_NAME "i18ngui.exe"
#define _I18NGUI_PUBLISHER ""

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
