# Options

`Cuneiform` accepts the following arguments:

## [input] {-}

The folder (or file) to analyze.

## \-\-enable {-}

The following checks can be toggled via the `--enable` argument.

{{< include checks.qmd >}}

## \-\-disable {-}

Which checks to not perform. (Refer to options available above.)
This will override any options passed to `--enable`.

## \-\-log-l10n-allowed {-}

Whether it is acceptable to pass translatable strings to logging functions.
Setting this to `false` will emit warnings when a translatable string is
passed to functions such as `wxLogMessage`, `g_message`, or `qCWarning`.

(Default is `true`.)

## \-\-punct-l10n-allowed {-}

Whether it is acceptable for punctuation only strings to be translatable.

Setting this to `true` will suppress warnings about strings such as "*? - ?*"
being available for localization.

(Default is `false`.)

## \-\-exceptions-l10n-required {-}

Whether to verify that exception messages are available for translation.

Setting this to `true` will emit warnings when untranslatable strings are
passed to various exception constructors or functions
(e.g., `AfxThrowOleDispatchException`).

(Default is `true`.)

## \-\-min-l10n-wordcount {-}

The minimum number of words that a string must have to be considered translatable.

Higher values for this will result in less strings being classified as
`notL10NAvailable` warnings.

(Default is `2`.)

## \-\-cpp-version {-}

The C++ standard that should be assumed when issuing deprecated macro warnings (`deprecatedMacro`).

For example, setting this to `2017` or higher will issue warnings for `WXUNUSED`, as it
can be replaced with `[[maybe_unused]]`. If setting this to `2014`, however, `WXUNUSED`
will be ignored since `[[maybe_unused]]` requires C++17.

(Default is `2014`.)

## \-\-fuzzy {-}

Whether to review fuzzy translations.

(Default is `false`.)

## \-i,\-\-ignore {-}

Folders and files to ignore (can be used multiple times).

::: {.notesection data-latex=""}
Folder and file paths must be absolute or relative to the folder being analyzed.
:::

## \-o,\-\-output {-}

The output report path, which can be either a CSV or tab-delimited text file.
(Format is deteremined by the file extention that you provide.)

Can either be a full path, or a file name within the current working directory.

## \-q,\-\-quiet {-}

Only print errors and the final output.

## \-v,\-\-verbose {-}

Display debug information.

## \-h,\-\-help {-}

Print usage.
