# Reviewing Output

After building, go into the "bin" folder and run this command to analyze the sample file:

``` {.bash filename="Terminal"}
$ quneiform ../samples -o results.txt
```

This will produce a "results.txt" file in the "bin" folder which contains tabular results. This file will contain warnings such as:

- `suspectL10NString`: indicates that the string "*GreaterThanOrEqualTo*" is inside of a `_()` macro, making it available for translation.
This does not appear to be something appropriate for translation; hence the warning.

- `suspectL10NUsage`: indicates that the string "*Invalid dataset passed to column filter.*" is being used in a call to `wxASSERT_MSG()`, which is a debug assert function.
Asserts normally should not appear in production releases and shouldn't be seen by end users; therefore, they should not be translated.

- `notL10NAvailable`: indicates that the string "*\'%s\': string value not found for \'%s\' column filter.*" is not wrapped in a `_()` macro and not available for localization.

- `deprecatedMacro`: indicates that the text-wrapping macro `wxT()` should be removed.

- `nonUTF8File`: indicates that the file contains extended ASCII characters, but is not encoded as UTF-8.
It is generally recommended to encode files as UTF-8, making them portable between compilers and other tools.

- `unencodedExtASCII`: indicates that the file contains hard-coded extended ASCII characters.
It is recommended that these characters be encoded in hexadecimal format to avoid character-encoding issues between compilers.

To look only for suspect strings that are exposed for translation and show the results in the console window:

``` {.bash filename="Terminal"}
$ quneiform ../samples --enable=suspectL10NString,suspectL10NUsage
```

To look for all issues except for deprecated macros:

``` {.bash filename="Terminal"}
$ quneiform ../samples --disable=deprecatedMacros
```

By default, `Quneiform` will assume that messages inside of various exceptions should be translatable.
If these messages are not exposed for localization, then a warning will be issued.

To consider exception messages as internal (and suppress warnings about their messages not being localizable) do the following:

``` {.bash filename="Terminal"}
$ quneiform ../samples --exceptions-l10n-required=false
```

Similarity, `Quneiform` will also consider messages inside of various logging functions to be allowable for translation.
The difference is that it will not warn if a message is not exposed for translation.
This is because log messages can serve a dual role of user-facing messages and internal messages meant for developers.

To consider all log messages to never be appropriate for translation, do the following:

``` {.bash filename="Terminal"}
$ quneiform ../samples --log-l10n-allowed=false
```

To display any code-formatting issues, enable them explicitly:

``` {.bash filename="Terminal"}
$ quneiform ../samples --enable=trailingSpaces,tabs,wideLine

or

$ quneiform ../samples --enable=allCodeFormatting
```

